### ISSUE TITLE
Parses wikitable cells as inline paragraphs if text contains a front slash (/)

### ISSUE THREAD

**Issue by benrichards86** [peter17/mediawiki-parser#4]
If a wikitable data cell contains a front slash (`/`) in its contents, it appears that the parser will take all the text starting at the front slash and continuing until the end of the line and treats that entire string as an inline paragraph. If there are multiple data cells specified in-line, it will treat the entire line as the text to output, even the data cell separator token (`||`). It appears to be an issue in mediawikiParser.py itself. Looking at the output from the text and html postprocessors reflects that it's interpreting the text in this way.

This parsing bug seems to only present itself when it is parsing tables. I haven't seen it occur with normal paragraphs or lists.

Here's a simplified testcase that exposes the issue:
```python
from mediawiki_parser.preprocessor import make_parser
preprocessor = make_parser({})

from mediawiki_parser.html import make_parser
parser = make_parser([], [], [], {}, {})

source = """
{|
|AB||CD
|-
|E/F||GH
|}
"""

preprocessed_text = preprocessor.parse(source)
output = parser.parse(preprocessed_text.leaves())

print output.value
```
Below is the HTML code that results:
```html
<body>
<table>
<tr>
	<td>AB</td>
	<td>CD</td>
</tr>
<tr>
	<td>E<p>/F||GH</p>
</td>
</tr>
</table>
</body>
```

The preferred output is that the second row should be rendered as such:
```html
<tr>
	<td>E/F</td>
	<td>GH</td>
</tr>
```

The test fails with the latest version of mediawiki-parser (d7fa6ffeb7daf1e5368feefcdd6fc4d37c18ab98) and pijnu (peter17/pijnu@25518c3d1ca10955af514b36132777f15027d42d).

**Comment by peter17** [comment]
Hi @benrichards86 
Thanks for reporting. This should be fixed now!
Regards.

**Comment by benrichards86** [comment]
Thank you!
